LANGUAGES = {
    "": {"name": "Norsk"},  # Default language

    "aar": {"name": "Afaraf"},
    "abk": {"name": "Аҧсуа"},
    "ace": {"name": "Bahsa Acèh"},
    "ach": {"name": "Lwo"},
    "ada": {"name": "Adangme"},
    "ady": {"name": "Адыгэбзэ"},
    "afr": {"name": "Afrikaans"},
    "ain": {"name": "アイヌ・イタㇰ"},
    "aka": {"name": "Akan"},
    "alb": {"name": "Shqip"},  # Also 'sqi'
    "amh": {"name": "አማርኛ"},
    "ara": {"name": "العربية"},
    "arg": {"name": "Aragonés"},
    "arm": {"name": "Հայերեն"},  # Also 'hye'
    "asm": {"name": "অসমীয়া"},
    "ava": {"name": "Авар мацӀ"},
    "ave": {"name": "avesta"},
    "aym": {"name": "Aymar aru"},
    "aze": {"name": "Azərbaycanca"},
    "bak": {"name": "Башҡорт теле"},
    "bam": {"name": "Bamanankan"},
    "baq": {"name": "Euskara"},  # Also 'eus'
    "bel": {"name": "Беларуская"},
    "ben": {"name": "বাংলা"},
    "bih": {"name": "भोजपुरी"},
    "bis": {"name": "Bislama"},
    "bod": {"name": "བོད་ཡིག"},  # Tibetan
    "bos": {"name": "Bosanski"},
    "bre": {"name": "Brezhoneg"},
    "bul": {"name": "Български"},
    "bur": {"name": "မြန်မာစာ"},  # Also 'mya'
    "cat": {"name": "Català"},
    "ces": {"name": "Čeština"},
    "cha": {"name": "Chamoru"},
    "che": {"name": "нохчийн мотт"},
    "chi": {"name": "中文"},  # Also 'zho'
    "chu": {"name": "Словѣньскъ"},
    "chv": {"name": "Чӑвашла"},
    "cor": {"name": "Kernewek"},
    "cos": {"name": "Corsu"},
    "cre": {"name": "Nehiyaw"},
    "cym": {"name": "Cymraeg"},
    "dan": {"name": "Dansk"},
    "deu": {"name": "Deutsch"},
    "div": {"name": "ދިވެހި"},
    "dut": {"name": "Nederlands"},  # Also 'nld'
    "dzo": {"name": "རྫོང་ཁ"},
    "ell": {"name": "Ελληνικά"},  # Also 'gre'
    "eng": {"name": "English"},
    "epo": {"name": "Esperanto"},
    "est": {"name": "Eesti"},
    "eus": {"name": "Euskara"},
    "ewe": {"name": "Eʋegbe"},
    "fao": {"name": "Føroyskt"},
    "fas": {"name": "فارسی"},  # Also 'per'
    "fij": {"name": "Na Vosa Vakaviti"},
    "fin": {"name": "Suomi"},
    "fra": {"name": "Français"},
    "fre": {"name": "Français"},  # Also 'fra'
    "fry": {"name": "Frysk"},
    "ful": {"name": "Fulfulde"},
    "geo": {"name": "ქართული"},  # Also 'kat'
    "ger": {"name": "Deutsch"},  # Also 'deu'
    "gla": {"name": "Gàidhlig"},
    "gle": {"name": "Gaeilge"},
    "glg": {"name": "Galego"},
    "glv": {"name": "Gaelg"},
    "gre": {"name": "Ελληνικά"},
    "grn": {"name": "Avañe'ẽ"},
    "guj": {"name": "ગુજરાતી"},
    "hat": {"name": "Kreyòl ayisyen"},
    "hau": {"name": "Hausa"},
    "heb": {"name": "עברית"},
    "her": {"name": "Otjiherero"},
    "hin": {"name": "हिन्दी"},
    "hmo": {"name": "Hiri Motu"},
    "hrv": {"name": "Hrvatski"},
    "hun": {"name": "Magyar"},
    "hye": {"name": "Հայերեն"},
    "ibo": {"name": "Igbo"},
    "ice": {"name": "Íslenska"},  # Also 'isl'
    "ido": {"name": "Ido"},
    "iii": {"name": "ꆈꌠ꒿ Nuosuhxop"},
    "iku": {"name": "ᐃᓄᒃᑎᑐᑦ"},
    "ind": {"name": "Bahasa Indonesia"},
    "ipk": {"name": "Iñupiatun"},
    "isl": {"name": "Íslenska"},
    "ita": {"name": "Italiano"},
    "jav": {"name": "Basa Jawa"},
    "jpn": {"name": "日本語"},
    "kal": {"name": "Kalaallisut"},
    "kan": {"name": "ಕನ್ನಡ"},
    "kas": {"name": "कश्मीरी"},
    "kat": {"name": "ქართული"},
    "kau": {"name": "Kanuri"},
    "kaz": {"name": "Қазақша"},
    "khm": {"name": "ភាសាខ្មែរ"},
    "kik": {"name": "Gĩkũyũ"},
    "kin": {"name": "Ikinyarwanda"},
    "kir": {"name": "Кыргызча"},
    "kom": {"name": "Коми кыв"},
    "kon": {"name": "Kikongo"},
    "kor": {"name": "한국어"},
    "kua": {"name": "Kuanyama"},
    "kur": {"name": "Kurdî"},
    "lao": {"name": "ພາສາລາວ"},
    "lat": {"name": "Latina"},
    "lav": {"name": "Latviešu"},
    "lim": {"name": "Limburgs"},
    "lin": {"name": "Lingála"},
    "lit": {"name": "Lietuvių"},
    "ltz": {"name": "Lëtzebuergesch"},
    "lub": {"name": "Kiluba"},
    "lug": {"name": "Luganda"},
    "mac": {"name": "Македонски"},  # Also 'mkd'
    "mah": {"name": "Kajin M̧ajeļ"},
    "mal": {"name": "മലയാളം"},
    "mar": {"name": "मराठी"},
    "mkd": {"name": "Македонски"},
    "mlg": {"name": "Malagasy"},
    "mlt": {"name": "Malti"},
    "mon": {"name": "Монгол"},
    "mri": {"name": "Te Reo Māori"},  # Also 'mao'
    "msa": {"name": "Bahasa Melayu"},
    "mya": {"name": "မြန်မာစာ"},
    "nau": {"name": "Ekakairũ Naoero"},
    "nav": {"name": "Diné bizaad"},
    "nbl": {"name": "isiNdebele"},
    "nde": {"name": "isiNdebele"},
    "ndo": {"name": "Owambo"},
    "nep": {"name": "नेपाली"},
    "nld": {"name": "Nederlands"},
    "nno": {"name": "Norsk nynorsk"},
    "nob": {"name": "Norsk bokmål"},
    "nor": {"name": "Norsk"},
    "nya": {"name": "ChiCheŵa"},
    "oci": {"name": "Occitan"},
    "oji": {"name": "ᐊᓂᔑᓈᐯᒧᐎᓐ"},
    "ori": {"name": "ଓଡ଼ିଆ"},
    "orm": {"name": "Afaan Oromoo"},
    "oss": {"name": "Ирон æвзаг"},
    "pan": {"name": "ਪੰਜਾਬੀ"},
    "per": {"name": "فارسی"},
    "pli": {"name": "पाऴि"},
    "pol": {"name": "Polski"},
    "por": {"name": "Português"},
    "pus": {"name": "پښتو"},
    "que": {"name": "Runa Simi"},
    "roh": {"name": "Rumantsch"},
    "ron": {"name": "Română"},
    "rum": {"name": "Română"},  # Also 'ron'
    "run": {"name": "Kirundi"},
    "rus": {"name": "Русский"},
    "sag": {"name": "Sängö"},
    "san": {"name": "संस्कृतम्"},
    "sin": {"name": "සිංහල"},
    "slk": {"name": "Slovenčina"},
    "slo": {"name": "Slovenčina"},  # Also 'slk'
    "slv": {"name": "Slovenščina"},
    "sme": {"name": "Davvisámegiella"},
    "smo": {"name": "Gagana Samoa"},
    "sna": {"name": "ChiShona"},
    "snd": {"name": "سنڌي"},
    "som": {"name": "Soomaaliga"},
    "sot": {"name": "Sesotho"},
    "spa": {"name": "Español"},
    "sqi": {"name": "Shqip"},
    "srd": {"name": "Sardu"},
    "srp": {"name": "Српски"},
    "ssw": {"name": "SiSwati"},
    "sun": {"name": "Basa Sunda"},
    "swa": {"name": "Kiswahili"},
    "swe": {"name": "Svenska"},
    "tah": {"name": "Reo Tahiti"},
    "tam": {"name": "தமிழ்"},
    "tat": {"name": "Татар теле"},
    "tel": {"name": "తెలుగు"},
    "tgk": {"name": "Тоҷикӣ"},
    "tgl": {"name": "Tagalog"},
    "tha": {"name": "ไทย"},
    "tib": {"name": "བོད་ཡིག"},
    "tir": {"name": "ትግርኛ"},
    "ton": {"name": "faka Tonga"},
    "tsn": {"name": "Setswana"},
    "tso": {"name": "Xitsonga"},
    "tuk": {"name": "Türkmençe"},
    "tur": {"name": "Türkçe"},
    "twi": {"name": "Twi"},
    "uig": {"name": "Uyƣurqə"},
    "ukr": {"name": "Українська"},
    "urd": {"name": "اردو"},
    "uzb": {"name": "Oʻzbek"},
    "ven": {"name": "Tshivenḓa"},
    "vie": {"name": "Tiếng Việt"},
    "vol": {"name": "Volapük"},
    "wel": {"name": "Cymraeg"},  # Also 'cym'
    "wln": {"name": "Walon"},
    "wol": {"name": "Wolof"},
    "xho": {"name": "isiXhosa"},
    "yid": {"name": "ייִדיש"},
    "yor": {"name": "Yorùbá"},
    "zha": {"name": "Saɯ cueŋƅ"},
    "zho": {"name": "中文"},
    "zul": {"name": "isiZulu"},
}