site_name: Piggy
site_url: https://piggy.iktim.no
site_description: >-
    En oppgavebank for IM og IKT ved Vågen VGS.
docs_dir: piggy

repo_name: piggy.iktim.no
repo_url: https://github.com/VaagenIM/piggy
edit_uri: edit/main/piggy/

copyright: >
  Copyright &copy; 2023 - 
  <a href="#__consent">Endre personvernsinnstillinger</a>

theme:
    name: material
    custom_dir: overrides
    language: 'nb'

    palette:  # Light/Dark Mode
    - media: "(prefers-color-scheme: light)"  # Light mode
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  # Dark mode
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode

    features:
        - content.action.edit       # Add edit page button
        - content.code.annotate     # Add annotations to codeblocks (```code (1)``` 1. annotation)
        - navigation.indexes        # Attach index.md to parent
        - navigation.tabs           # Subdirectories of docs/ as tabs
        - navigation.tracking       # Automatically add #anchor to URL while scrolling
        - navigation.top            # Back to top button
        - navigation.prune          # Performance / size optimization
        - navigation.footer         # Next / previous page footer
        - search.suggest            # Autocomplete results during search
        - search.highlight          # Highlight occurences inside clicked search result
        - search.share              # Share search URL button in text input

    logo: logo.webp
    favicon: logo.webp

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/VaagenIM
      name: "@VaagenIM"
  alternate:
    - name: Norsk
      link: '%GT_RELATIVE_URL%'
      lang: 'no'
    - name: English
      link: 'https://translate.goog/?_x_tr_sl=no&_x_tr_tl=en'
      lang: 'en'
  consent:
    title: Samtykke til informasjonskapsler
    actions:
      - accept
      - reject
      - manage
    description: >- 
      Vi bruker informasjonskapsler for å gjenkjenne dine gjentatte besøk og preferanser, 
      samt for å måle effektiviteten til innholdet og om brukerne finner det de leter etter. 
      Med ditt samtykke hjelper du oss forbedre innholdet på siden.
      
      
markdown_extensions:
  # Essentials
  - meta                        # Load frontmatter (---\ntitle: Title\n---
  - attr_list                   # Add HTML attributes to anything (![image](link) { align=left })
  - nl2br                       # All linebreaks add <br> tags (starts new line on new lines...)
  - mdx_breakless_lists         # single linebreak required for lists, instead of two
  - pymdownx.magiclink          # Automatically wrap links to <a> tags https://google.com = <a href="https://google.com">https://google.com</a>

  # Features
  - footnotes                   # Citations (Zotero/Pandoc) ([^1], [^1]: Lorem ipsum)
  - admonition                  # Callout blocks > [!INFO], > [!WARNING], > [!VIDEO], > [!TECH], > [!CODE] (alt: !!! type)
  - pymdownx.details            # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#configuration
  - pymdownx.tasklist:          # - [ ] Task, - [x] Task completed
      custom_checkbox: true         # https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists

  # Code highlighting
  - pymdownx.superfences        # Code higlighting ```language\n code\n ```
  - pymdownx.highlight:         # Syntax highlighting + superfences
      linenums: true                # numbered lines
      anchor_linenums: true         # generate anchor links to line number
  - pymdownx.inlinehilite       # Inline code highlighting
  # Math / Formulas

  - pymdownx.arithmatex:        # Mathematical formulas $f(a)=f(b)$ $5*2=10$
      generic: true             # Clean formatting for non-MathJax libraries

  # ^~= modifiers
  - pymdownx.caret              # ^^underline^^, ^superscript^ (H^2^O)
  - pymdownx.tilde              # ~~strikethrough~~, ~subscript~ (~2~OH)
  - pymdownx.mark               # ==mark text== (yellow marker)
  - pymdownx.betterem:          # **bold** *italic*, __bold__ _italic_
      smart_enable: all             # Both modifiers (* and _)

  # Extra
  - pymdownx.keys               # ++ctrl+alt+delete++
  - pymdownx.smartsymbols       # Convert special characters from markdown ((tm) = ™)
  - smarty                      # '' -> ‘’, "" -> “”, etc..
  - pymdownx.emoji:             # Emojis :smile: :tada:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
    - search                        # Search bar
    - awesome-pages                 # Automatically generate nav
    - google-translate:             # Relative paths for google translate
        url: 'piggy.iktim.no'
    - tags                          # Searchable tags
    - callouts                      # Convert obsidian callouts to markdown format
    - roamlinks                     # Use WikiLinks
    - glightbox:                    # Lightbox! https://github.com/blueswen/mkdocs-glightbox
    - footermatter:                 # Last edited, date created, author links. Needs to be updated for proper author rendering
        default_author_img: https://ui-avatars.com
        default_author_url: https://github.com/VaagenIM/piggy
        date_format: 'timeago'
        locale: 'nb_NO'
        author_map:                 # Name in frontmatter | path RELATIVE TO: resources/assets/authors or URL | website
          - Sondre Grønås | https://www.gravatar.com/avatar/4e0476393c848aef61ed66d404da0d14?s=250 | https://github.com/sondregronas
    - exclude:                      # Exclude pattern from site
        glob:
          - .obsidian/*
          - _DATA/*
        regex:
          - '.*\.(tmp|bin|tar)$'
    - minify:                       # Optimize load times
        minify_html: true

nav:
  - Home:
      - index.md
      - levering.md
  - ...